version: '3.2'
services:
  pgsql:
    image: clonm/postgresql:10
      #double check using right tag.
    volumes:
      - ./development/postgresql:/var/lib/postgresql
      - ./development/log:/var/log/postgresql
      #- development/postgresql:
      #  bind: ./var/lib/postgresql
      #  user: 102
      #  group: 106
      #- development/log:
      #  bind: ./var/log/postgresql
      #  user: nobody
      #  group: nogroup

  sympa:
    build: .
    depends_on:
         - pgsql

    container_name: sympa

    ports:
      - "80:80"

    # network_mode:
    #   name: server2.cloyne.org
    environment:
      VIRTUAL_HOST: localhost
      REMOTE_ADDR: localhost
      VIRTUAL_ALIAS: /lists,/lists-static/
      SET_REAL_IP_FROM: 172.18.0.0/16
      ADMINADDR: closoft@bsc.coop
        #type: pillar
        #key: mailer:root_alias
        #join: ','
      #remotes needs to be changed
      REMOTES:
        # type: pillar
        # key: mailer:relay
    volumes:
      - ./etc/shared:/etc/sympa/shared #read about this in tozd readme
      - ./development/log/sympa:/var/log/sympa
      - ./development/log/sympa/nginx:/var/log/nginx
      - ./development/data:/var/lib/sympa
      - ./development/nullmailer:/var/spool/nullmailer
      - ./development/spool:/var/spool/sympa
      - ./etc/includes:/etc/sympa/includes
    networks:
      - server2.cloyne.org
networks:
  server2.cloyne.org:
    external: true

